### Experiment 4
1. maxproduct composition
2. maxmin composition

In [12]:
import numpy as np

In [133]:
def maxproduct(a, b):
    # a is a matrix of size (x,y)
    # b is a matrix of size (u,v)
    
    if a.ndim < 2:
        a = np.atleast_2d(s)
    
    if b.ndim < 2:
        b = np.atleast_2d(b)
    
    # r is the maxproduct of size (x,v)
    m = a.shape[0]
    n = b.shape[1]
    
    # creating a matrix of size (x, v) filled with zeros
    r = np.zeros((m, n))
    
    for i in range(m):
        for j in range(n):
            # the resultant is each max(a.row x b.column)
            r[i, j] = np.amax(np.multiply(a[i,:], np.transpose(b[:,j])))
    
    return r

In [144]:
def maxmin(a, b):
    if a.ndim < 2:
        a = np.atleast_2d(a)
        
    if b.ndim < 2:
        b = np.atleast_2d(b)
        
    m = a.shape[0]
    n = b.shape[1]
    
    r = np.zeros((m, n))
    
    for i in range(m):
        for j in range(n):
            # the resultant matrix is max(min(a[i, k], b[k, j]))
            r[i, j] = np.amax(np.fmin(a[i,:], b[:,j]))
            
    return r

In [145]:
a = np.asarray([[0.1, 0.2, 0.0, 1.0], [0.3, 0.3, 0.0, 0.2], [0.8, 0.9, 1.0, 0.4]])
a

array([[ 0.1,  0.2,  0. ,  1. ],
       [ 0.3,  0.3,  0. ,  0.2],
       [ 0.8,  0.9,  1. ,  0.4]])

In [146]:
b = np.asarray([[0.9, 0.0, 0.3], [0.2, 1.0, 0.8], [0.8, 0.0, 0.7], [0.4, 0.2, 0.3]])
b

array([[ 0.9,  0. ,  0.3],
       [ 0.2,  1. ,  0.8],
       [ 0.8,  0. ,  0.7],
       [ 0.4,  0.2,  0.3]])

In [147]:
maxproduct(a, b)

array([[ 0.4 ,  0.2 ,  0.3 ],
       [ 0.27,  0.3 ,  0.24],
       [ 0.8 ,  0.9 ,  0.72]])

In [148]:
maxmin(a, b)

array([[ 0.4,  0.2,  0.3],
       [ 0.3,  0.3,  0.3],
       [ 0.8,  0.9,  0.8]])